#pragma once
#include <string>
#include <vector>

namespace bp {

// Per-slot timing configuration for a transmitter site.
// One site may transmit on multiple slots (colocated transmitters sharing a mast).
struct SlotConfig {
    int    slot             = 1;     // 1–24
    bool   is_master        = false;
    int    master_slot      = 0;     // 0 = none; set when is_master is false
    double spo_us           = 0.0;
    double station_delay_us = 0.0;
};

// A physical transmitter site.  One site may carry one or more slots
// (e.g. a dual-frequency mast transmitting on both slot 1 and slot 5).
// Name, position, antenna height, and power are site-level properties.
struct TransmitterSite {
    std::string name;
    double lat           = 0.0;
    double lon           = 0.0;
    // Informational OSGB easting/northing (computed from lat/lon, not stored as canonical)
    double osgb_easting  = 0.0;
    double osgb_northing = 0.0;
    double power_w       = 40.0;
    double height_m      = 50.0;
    bool   locked        = false;  // position locked — not draggable on map
    std::vector<SlotConfig> slots;

    bool is_multi_slot() const { return slots.size() > 1; }
    int  slot_count()    const { return (int)slots.size(); }
};

// Flat view of a single (site + slot) pair, used by the physics pipeline.
// Generated by Scenario::flatTransmitters(); not stored directly in the scenario.
struct Transmitter {
    std::string name;
    double lat           = 0.0;
    double lon           = 0.0;
    double osgb_easting  = 0.0;
    double osgb_northing = 0.0;
    double power_w          = 40.0;
    double height_m         = 50.0;
    int    slot             = 1;     // 1–24
    bool   is_master        = false;
    int    master_slot      = 0;     // 0 = none
    double spo_us           = 0.0;
    double station_delay_us = 0.0;
    bool   locked           = false;
};

} // namespace bp
